version: '3'
services:
  tileserver:
    image: maptiler/tileserver-gl
    command: ["tileserver-gl", "--port", "3650"]
    ports:
      - "3650:3650"
    volumes:
      - .:/data
    restart: unless-stopped
